// deno-lint-ignore-file no-explicit-any
import { allowedPathDefaults, suspiciousPathDefaults } from "./pathlist.ts";

export const defaults: Record<string, number> = {
  enabled: 1,
  warnScore: 40,
  blockScore: 120,
  delayStartScore: 20,
  delayFactorMs: 60,
  maxDelayMs: 6000,
  decayPerMin: 2,
  userScorePercent: 50,
  ipScorePercent: 100,
  rangeScorePercent: 35,
  pathScorePercent: 15,
  pathDelayStartScore: 200,
  pathDelayFactorMs: 10,
  pathMaxDelayMs: 1200,
  clientScorePercent: 70,
  userBucketPercent: 45,
  attackScorePercent: 100,
  loginScorePercent: 100,
  attackBlockConfidence: 92,
  pathBlockSeconds: 900,
  pathBlockMax: 5000,
  settingCacheSeconds: 5,
  bucketCacheSeconds: 2,
  requestWarnMs: 1500,
  requestMaxMs: 10000,
  slowMs: 1500,
  largeBody: 2 * 1024 * 1024,
  keepDays: 30,
};

export const textDefaults: Record<string, string> = {
  suspiciousPaths: suspiciousPathDefaults.join("\n"),
  allowedPaths: allowedPathDefaults.join("\n"),
};

export const settingInfo: Record<string, [string, string]> = {
  enabled: ["Aktiv", "0/1"],
  warnScore: ["Warnung ab Score", "score"],
  blockScore: ["Block ab Score", "score"],
  delayStartScore: ["Delay ab Score", "score"],
  delayFactorMs: ["Delay Faktor", "ms/score"],
  maxDelayMs: ["Max Delay", "ms"],
  decayPerMin: ["Score-Abbau", "score/min"],
  userScorePercent: ["Login-Faktor", "%"],
  ipScorePercent: ["IP-Gewicht", "%"],
  rangeScorePercent: ["Range-Gewicht", "%"],
  pathScorePercent: ["Pfad-Gewicht", "%"],
  pathDelayStartScore: ["Pfad Delay ab", "score"],
  pathDelayFactorMs: ["Pfad Delay Faktor", "ms/score"],
  pathMaxDelayMs: ["Pfad Max Delay", "ms"],
  clientScorePercent: ["Client-Gewicht", "%"],
  userBucketPercent: ["User-Gewicht", "%"],
  attackScorePercent: ["Attack-Gewicht", "%"],
  loginScorePercent: ["Login-Gewicht", "%"],
  attackBlockConfidence: ["Attack Sofortblock", "confidence"],
  pathBlockSeconds: ["Pfadblock Dauer", "s"],
  pathBlockMax: ["Pfadblock Speicher", "max"],
  settingCacheSeconds: ["Settings Cache", "s"],
  bucketCacheSeconds: ["Bucket Cache", "s"],
  requestWarnMs: ["Request Warnzeit", "ms"],
  requestMaxMs: ["Request Maxzeit", "ms"],
  slowMs: ["Legacy Slowzeit", "ms"],
  largeBody: ["Grosser Body", "bytes"],
  keepDays: ["Aufbewahrung", "days"],
};

export const dbSchema = {
  properties: {
    m_security_event: {
      additionalProperties: {
        properties: {
          id: { type: "integer", "x-index": "primary", "x-autoincrement": true },
          log_id: { type: "integer", "x-index": true, "x-qg-parent": "log", "x-qg-on-parent-delete": "setnull" },
          time: { type: "integer", "x-index": true },
          prio: { type: "string", maxLength: 16, "x-index": true },
          kind: { type: "string", maxLength: 32, "x-index": true },
          scope: { type: "string", maxLength: 16, "x-index": true },
          ident: { type: "string", maxLength: 191, "x-index": true },
          reason: { type: "string", maxLength: 191, "x-index": true },
          state: { type: "string", maxLength: 16, "x-index": true },
          confidence: { type: "integer", "x-index": true },
          severity: { type: "integer", "x-index": true },
          score: { type: "integer" },
          delay_ms: { type: "integer" },
          blocked: { type: "boolean", "x-index": true },
          ip: { type: "string", maxLength: 64, "x-index": true },
          ip_range: { type: "string", maxLength: 64, "x-index": true },
          client_id: { type: "integer", "x-index": true },
          sess_id: { type: "integer", "x-index": true },
          usr_id: { type: "integer", "x-index": true },
          method: { type: "string", maxLength: 8 },
          path: { type: "string", maxLength: 512, "x-index": true },
          status: { type: "integer", "x-index": true },
          duration_ms: { type: "integer", "x-index": true },
          bytes_in: { type: "integer" },
          bytes_out: { type: "integer" },
          ua: { type: "string" },
          data: { type: "string" },
        },
        required: ["id", "time", "prio", "kind", "scope", "ident", "reason", "state", "confidence", "severity", "score", "delay_ms", "blocked", "ip", "ip_range", "method", "path", "status", "duration_ms", "bytes_in", "bytes_out", "ua", "data"],
      },
    },
    m_security_bucket: {
      additionalProperties: {
        properties: {
          id: { type: "integer", "x-index": "primary", "x-autoincrement": true },
          scope: { type: "string", maxLength: 16, "x-index": true },
          ident: { type: "string", maxLength: 191, "x-index": true },
          score: { type: "integer", "x-index": true },
          count: { type: "integer", "x-index": true },
          blocked: { type: "boolean", "x-index": true },
          first_seen: { type: "integer", "x-index": true },
          last_seen: { type: "integer", "x-index": true },
          reason: { type: "string", maxLength: 191, "x-index": true },
          sample_path: { type: "string", maxLength: 512 },
          data: { type: "string" },
        },
        required: ["id", "scope", "ident", "score", "count", "blocked", "first_seen", "last_seen", "reason", "sample_path", "data"],
      },
    },
    m_security_setting: {
      additionalProperties: {
        properties: {
          name: { type: "string", maxLength: 64, "x-index": "primary" },
          value: { type: "string" },
        },
        required: ["name", "value"],
      },
    },
  },
};
