import { cms } from "@qino/qino/cms";

import type { Node } from "@qino/qino/cms";
import type { Seed } from "../seed.ts";

/** Every language gets its own text — a one-language install simply gets one. */
async function title(s: Seed, node: Node, text: string): Promise<void> {
  const def = s.app.languages.def;
  for (const lang of s.app.languages.all) await node.title(lang, lang === def ? text : `${text} [${lang}]`);
}
async function text(s: Seed, node: Node, name: string, value: string): Promise<void> {
  const def = s.app.languages.def;
  for (const lang of s.app.languages.all) await node.text(name, lang, lang === def ? value : `<p><i>[${lang}]</i></p>\n${value}`);
}

/** A layout the installation actually has. Backend and login layouts are not site layouts. */
function layout(s: Seed): string | undefined {
  const all = Object.keys(cms(s.app).getLayouts()).filter((n) => !/\.(backend|login)$/.test(n));
  return all.find((n) => n === "cms.layout.custom.9") ?? all[0];
}

/** Files hung on the page itself — the file browser and the cleanup views want something to show. */
async function attach(s: Seed, page: Node, n: number, label: string): Promise<void> {
  for (let i = 1; i <= n; i++) {
    await page.addFile(s.rnd.image(`${label}-${i}`, `${label} ${i}`, 1200, 800), `download_${i}`);
    s.count("files");
  }
}

type ContSpec = { module: string; text?: string; table?: [number, number]; image?: string; settings?: Record<string, unknown> };

/** Fill a page's main container. Contents whose module is not installed are left out. */
async function contents(s: Seed, page: Node, specs: ContSpec[]): Promise<void> {
  const main = await page.cont("main");
  let i = 0;
  for (const spec of specs) {
    if (!s.module(spec.module)) continue;
    const cont = await main.cont(String(++i), spec.module);
    s.count("contents");
    for (const [key, value] of Object.entries(spec.settings ?? {})) cont.settings[key](value);
    if (spec.text) await text(s, cont, "main", spec.text);
    if (spec.image) {
      for (const lang of s.app.languages.all) {
        await (await cont.file("image_" + lang)).replaceBy(s.rnd.image(spec.image, `${spec.image} ${lang}`));
      }
      s.count("files", s.app.languages.all.length);
    }
    if (spec.table) {
      const [rows, cols] = spec.table;
      cont.settings.rows(rows);
      cont.settings.cols(cols);
      for (let r = 0; r < rows; r++) {
        for (let c = 0; c < cols; c++) await text(s, cont, `${r}_${c}`, r === 0 ? `<b>${s.rnd.title(1)}</b>` : s.rnd.words(s.rnd.int(1, 3)));
      }
    }
  }
}

const prose = (s: Seed): ContSpec[] => [
  { module: "cms.cont.text", text: s.rnd.richText() },
];
const illustrated = (s: Seed, label: string): ContSpec[] => [
  { module: "cms.cont.image2", image: label },
  { module: "cms.cont.text", text: s.rnd.richText() },
];

export async function run(s: Seed): Promise<void> {
  const cm = cms(s.app);
  const module = layout(s);
  const site = await cm.node(1);
  if (!site.exists()) return;

  const page = async (parent: Node, name: string, vs: Record<string, unknown> = {}) => {
    const node = await parent.createChild({ access: 1, visible: true, searchable: true, ...(module ? { module } : {}), ...vs });
    await title(s, node, name);
    s.pages.push(node);
    s.count("pages");
    return node;
  };

  const root = await page(site, "Demo site", { sort: 900 });
  s.root = root;
  await contents(s, root, [
    { module: "cms.cont.text", text: `<h2>Demo content</h2>\n<p>Everything below this page was generated by <code>cms.backend.demo</code>. Reset it from the backend at any time.` },
    { module: "cms.cont.nav3", settings: { level: 2 } },
    ...illustrated(s, "Demo site"),
  ]);
  for (const [name, level] of [["Demo editors", 2], ["Demo authors", 1]] as const) {
    const grp = s.grps.get(name);
    if (grp) await root.changeGroup(grp, level);
  }

  // A section of ordinary pages, each with a little of everything
  const about = await page(root, "About us");
  await contents(s, about, illustrated(s, "About us"));
  const team = await page(about, "Team");
  await contents(s, team, prose(s));
  for (let i = 0; i < s.many(8); i++) {
    const { firstname, lastname, city } = s.rnd.person();
    const person = await page(team, `${firstname} ${lastname}`);
    await contents(s, person, [
      { module: "cms.cont.image2", image: `${firstname} ${lastname}` },
      { module: "cms.cont.text", text: `<p><b>${firstname} ${lastname}</b>, ${city}</p>\n${s.rnd.richText(2)}` },
    ]);
  }
  await contents(s, await page(about, "History"), prose(s));
  await contents(s, await page(about, "Jobs", { visible: false }), prose(s));

  const services = await page(root, "Services");
  await contents(s, services, [{ module: "cms.cont.nav3", settings: { startLevel: 1 } }, ...prose(s)]);
  for (let i = 0; i < s.many(4); i++) {
    await contents(s, await page(services, s.rnd.title(2)), illustrated(s, `Service ${i + 1}`));
  }

  // Many siblings, spread over two years — a list long enough to page through
  const blog = await page(root, "Blog");
  await contents(s, blog, [{ module: "cms.cont.nav3", settings: { startLevel: 1, level: 1 } }]);
  for (let i = 0; i < s.many(18); i++) {
    const post = await page(blog, s.rnd.topic(i + 1), {
      online_start: s.rnd.past(730, s.now),
      visible: s.rnd.chance(0.9),
      ...(s.rnd.chance(0.1) ? { online_end: s.rnd.past(30, s.now) } : {}), // a few expired ones
    });
    await contents(s, post, s.rnd.chance(0.5) ? illustrated(s, `Post ${i + 1}`) : prose(s));
  }

  const products = await page(root, "Products");
  await contents(s, products, [...prose(s), { module: "cms.cont.table2", table: [6, 4] }]);
  for (let i = 0; i < s.many(10); i++) {
    const product = await page(products, `${s.rnd.title(1)} ${100 + i}`);
    await attach(s, product, 1, `product-${100 + i}`);
    await contents(s, product, [
      { module: "cms.cont.image2", image: `Product ${100 + i}` },
      { module: "cms.cont.text", text: s.rnd.richText(2) },
      { module: "cms.cont.table2", table: [4, 2] },
    ]);
  }

  // Restricted: invisible to guests, readable for members, editable for editors
  const members = await page(root, "Members area", { access: 0 });
  await contents(s, members, prose(s));
  for (const [name, level] of [["Demo members", 1], ["Demo editors", 2]] as const) {
    const grp = s.grps.get(name);
    if (grp) await members.changeGroup(grp, level);
  }
  const downloads = await page(members, "Downloads", { access: null });
  await contents(s, downloads, prose(s));
  await attach(s, downloads, s.many(4), "download");
  const personal = await page(members, "Personal note", { access: 0 });
  if (s.usrs[0]) await personal.changeUser(s.usrs[0].id, 1);
  await contents(s, personal, prose(s));

  const legal = await page(root, "Legal", { visible: false });
  for (const name of ["Privacy", "Terms", "Imprint"]) await contents(s, await page(legal, name, { searchable: false }), prose(s));

  // Corner cases worth having in a test site
  const odd = await page(root, "Edge cases", { visible: false });
  await contents(s, await page(odd, "Ünïcode — ümlauts, ñ, 日本語, emoji 🎈"), prose(s));
  await contents(s, await page(odd, s.rnd.words(24)), prose(s)); // a title far too long
  await contents(s, await page(odd, "Offline page", { online_end: s.rnd.past(10, s.now) }), prose(s));
  await contents(s, await page(odd, "Future page", { online_start: s.now + 30 * 86400 }), prose(s));
  await contents(s, await page(odd, "Empty page"), []);
  const custom = await page(odd, "Custom url");
  for (const lang of s.app.languages.all) await custom.urlSet(lang, { url: `${lang}/demo-custom-url`, custom: true });
  await contents(s, custom, prose(s));

  // Five levels deep, to see what a tree view does with it
  let deep = await page(odd, "Deep 1");
  for (let i = 2; i <= 5; i++) {
    await contents(s, deep, prose(s));
    deep = await page(deep, `Deep ${i}`);
  }
  await contents(s, deep, prose(s));

  if (s.table("page_redirect")) {
    await s.db.table("page_redirect").insert({ request: "demo", redirect: String(root) });
    s.count("redirects");
  }
}
